[package]
name = "languages"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
once_cell = "1.18"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
